DROP TABLE person;
DROP TABLE geoLocations;
DROP TABLE geoLocation;
DROP TABLE tag;

CREATE TABLE person (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

	name varchar(80) NULL,
	email varchar(80) NULL
);

CREATE TABLE geoLocations (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
	ownerId int NOT NULL FOREIGN KEY REFERENCES person(id) ON DELETE CASCADE,

	path boolean NULL,

	name varchar(80) NULL,
	description varchar(200) NULL,

	date date NULL,
	time time NULL,
	zone varchar(20) NULL,
);

CREATE TABLE geoLocation (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
	ownerId int NOT NULL FOREIGN KEY REFERENCES geoLocations(id) ON DELETE CASCADE,

	name varchar(80) NULL,
	description varchar(200) NULL,
	
	latitude decimal NOT NULL,
	longitude decimal NOT NULL,
	elevation int NULL,

	date date NULL,
	time time NULL,
	zone varchar(20) NULL,
);

CREATE TABLE tag (
	ownerId int NOT NULL,
	ownerType char(3),

	tag varchar(15) NULL,
);
